In [2]:
import numpy as np

In [3]:
my_list = [1,2,5,8,456]
np_arr_1 = np.array(my_list)

In [4]:
np_arr_1

array([  1,   2,   5,   8, 456])

In [6]:
np.arange(0, 50, 4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [8]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.linspace(0,30,5)

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.randn(3,3)

array([[-1.35055716, -1.07050201,  0.64277489],
       [ 0.2834732 , -0.56533139, -0.38111396],
       [ 0.51166836, -0.88949417,  1.04836951]])

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr = arr.reshape(5,5)

In [31]:
arr.dtype

dtype('int32')

In [32]:
arr8 = arr.astype(np.int8)

In [37]:
arr8.dtype

dtype('int8')